# Generated by Django 3.2 on 2024-06-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('id',), 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
